//||... ar lang ...||
Map<String, String> ar = {
  'Profile': 'الملف الشخصي',
  'Name': 'الاسم',
  'Enter name': 'ادخل الاسم',
  'Name is required': 'الاسم مطلوب',
  'Save': 'حفظ',
  'Saving': 'جاري الحفظ',
  'Something went wrong': 'حدث خطأ ما',
  'Home': 'الرئيسية',
  'Categories': 'الفئات',
  'No categories found': 'لم يتم العثور على فئات',
  'Products': 'المنتجات',
  'No products found': 'لم يتم العثور على منتجات',
  'My Orders': 'طلباتي',
  'Favorite': 'المفضلة',
  'Settings': 'الإعدادات',
  'Sign Out': 'تسجيل الخروج',
  'Signing Out': 'جاري تسجيل الخروج',
  'Are you sure you want to sign out from this account?':
      'هل أنت متأكد أنك تريد تسجيل الخروج من هذا الحساب؟',
  'We sent a verification code to this number @phone':
      'لقد قمنا بإرسال رمز التحقق إلى هذا الرقم @phone',
  'Send': 'إرسال',
  'Sign In': 'تسجيل الدخول',
  'Phone Number': 'رقم الهاتف',
  'Enter phone number': 'ادخل رقم الهاتف',
  'Phone number is required': 'رقم الهاتف مطلوب',
  'You dont have an account?': 'ليس لديك حساب؟',
  'Sign Up': 'إنشاء حساب',
  'Phone number does not exist': 'رقم الهاتف غير موجود',
  'Do you have an account?': 'هل لديك حساب؟',
  'Phone already exist': 'رقم الهاتف موجود بالفعل',
  'Checkout': 'الدفع',
  'Address': 'العنوان',
  'Product Specifications': 'مواصفات المنتج',
  'Summary': 'الملخص',
  'Delivery time': 'وقت التوصيل',
  'Not found': 'غير موجود',
  'Total product cost': 'إجمالي تكلفة المنتجات',
  'S.R': 'ر.س',
  'Delivery total cost': 'إجمالي تكلفة التوصيل',
  'Total': 'الإجمالي',
  'Confirm Order': 'تأكيد الطلب',
  'Please add an address to the order': 'يرجى إضافة عنوان للطلب',
  'Please add product specifications to the order':
      'يرجى إضافة مواصفات المنتج للطلب',
  'Are you sure you want to complete this order?':
      'هل أنت متأكد أنك تريد إتمام هذا الطلب؟',
  'Confirm': 'تأكيد',
  'Confirming': 'جاري التأكيد',
  'Order created successfully': 'تم إنشاء الطلب بنجاح',
  'Favorite is empty': 'المفضلة فارغة',
  'No orders found': 'لم يتم العثور على طلبات',
  'Product Details': 'تفاصيل المنتج',
  'Suggested Products': 'المنتجات المقترحة',
  'No suggested product found': 'لم يتم العثور على منتج مقترح',
  'Remove from favorite': 'إزالة من المفضلة',
  'Add to favorite': 'إضافة إلى المفضلة',
  'Buy Now': 'اشتر الآن',
  'Add New Address': 'إضافة عنوان جديد',
  'Country': 'الدولة',
  'Enter country': 'ادخل اسم الدولة',
  'Country is required': 'الدولة مطلوبة',
  'City': 'المدينة',
  'Enter city': 'ادخل اسم المدينة',
  'City is required': 'المدينة مطلوبة',
  'Region': 'المنطقة',
  'Enter region': 'ادخل اسم المنطقة',
  'Region is required': 'المنطقة مطلوبة',
  'Street': 'الشارع',
  'Enter street': 'ادخل اسم الشارع',
  'Street is required': 'الشارع مطلوب',
  'Zip Code': 'الرمز البريدي',
  'Enter zip code': 'ادخل الرمز البريدي',
  'Zip code is required': 'الرمز البريدي مطلوب',
  'Add Product Specifications': 'إضافة مواصفات المنتج',
  'Quantity': 'الكمية',
  'ex: 5 pieces': 'مثال: 5 قطع',
  'Quantity is required': 'الكمية مطلوبة',
  'Product Color': 'لون المنتج',
  'Color is required': 'اللون مطلوب',
  'ex: black': 'مثال: أسود',
  'ex: xxl': 'مثال: كبير جداً',
  'Size is required': 'الحجم مطلوب',
  'Remove From Favorite': 'إزالة من المفضلة',
  'Are you sure you want to remove this product from favorite?':
      'هل أنت متأكد أنك تريد إزالة هذا المنتج من المفضلة؟',
  'Remove': 'إزالة',
  'Cancel': 'إلغاء',
  'Search here...': 'البحث هنا...',
  'Please Wait': 'يرجى الانتظار',
  'Product removed from favorite': 'تم حذف المنتج من المفضلة',
  'Product add to favorite': 'تمت اضافة المنتج الى المفضلة',
  'DISMISS': 'تجاهل',
  'Change Language': 'تغيير اللغة',
  'Products not found': 'لا يوجد منتجات',
  'Size': 'الحجم',
  'Select': 'اختيار',
  'Gallery': 'المعرض',
  'Camera': 'الكاميرا',
  'Verification Code': 'رمز التحقق',
};
