//||... en lang ...||
Map<String, String> en = {
  'Profile': 'Profile',
  'Name': 'Name',
  'Enter name': 'Enter name',
  'Name is required': 'Name is required',
  'Save': 'Save',
  'Saving': 'Saving',
  'Something went wrong': 'Something went wrong',
  'Home': 'Home',
  'Categories': 'Categories',
  'No categories found': 'No categories found',
  'Products': 'Products',
  'No products found': 'No products found',
  'My Orders': 'My Orders',
  'Favorite': 'Favorite',
  'Settings': 'Settings',
  'Sign Out': 'Sign Out',
  'Signing Out': 'Signing Out',
  'Are you sure you want to sign out from this account?':
      'Are you sure you want to sign out from this account?',
  'We sent a verification code to this number @phone':
      'We sent a verification code to this number @phone',
  'Send': 'Send',
  'Sign In': 'Sign In',
  'Phone Number': 'Phone Number',
  'Enter phone number': 'Enter phone number',
  'Phone number is required': 'Phone number is required',
  'You dont have an account?': 'You dont have an account?',
  'Sign Up': 'Sign Up',
  'Phone number does not exist': 'Phone number does not exist',
  'Do you have an account?': 'Do you have an account?',
  'Phone already exist': 'Phone already exist',
  'Checkout': 'Checkout',
  'Address': 'Address',
  'Product Specifications': 'Product Specifications',
  'Summary': 'Summary',
  'Delivery time': 'Delivery time',
  'Not found': 'Not found',
  'Total product cost': 'Total product cost',
  'S.R': 'S.R',
  'Delivery total cost': 'Delivery total cost',
  'Total': 'Total',
  'Confirm Order': 'Confirm Order',
  'Please add an address to the order': 'Please add an address to the order',
  'Please add product specifications to the order':
      'Please add product specifications to the order',
  'Are you sure you want to complete this order?':
      'Are you sure you want to complete this order?',
  'Confirm': 'Confirm',
  'Confirming': 'Confirming',
  'Order created successfully': 'Order created successfully',
  'Favorite is empty': 'Favorite is empty',
  'No orders found': 'No orders found',
  'Product Details': 'Product Details',
  'Suggested Products': 'Suggested Products',
  'No suggested product found': 'No suggested product found',
  'Remove from favorite': 'Remove from favorite',
  'Add to favorite': 'Add to favorite',
  'Buy Now': 'Buy Now',
  'Add New Address': 'Add New Address',
  'Country': 'Country',
  'Enter country': 'Enter country',
  'Country is required': 'Country is required',
  'City': 'City',
  'Enter city': 'Enter city',
  'City is required': 'City is required',
  'Region': 'Region',
  'Enter region': 'Enter region',
  'Region is required': 'Region is required',
  'Street': 'Street',
  'Enter street': 'Enter street',
  'Street is required': 'Street is required',
  'Zip Code': 'Zip Code',
  'Enter zip code': 'Enter zip code',
  'Zip code is required': 'Zip code is required',
  'Add Product Specifications': 'Add Product Specifications',
  'Quantity': 'Quantity',
  'ex: 5 pieces': 'ex: 5 pieces',
  'Quantity is required': 'Quantity is required',
  'Product Color': 'Product Color',
  'Color is required': 'Color is required',
  'ex: black': 'ex: black',
  'ex: xxl': 'ex: xxl',
  'Size is required': 'Size is required',
  'Remove From Favorite': 'Remove From Favorite',
  'Are you sure you want to remove this product from favorite?':
      'Are you sure you want to remove this product from favorite?',
  'Remove': 'Remove',
  'Cancel': 'Cancel',
  'Search here...': 'Search here...',
  'Please Wait': 'Please Wait',
  'Product removed from favorite': 'Product removed from favorite',
  'Product add to favorite': 'Product add to favorite',
  'DISMISS': 'DISMISS',
  'Change Language': 'Change Language',
  'Products not found': 'Products not found',
  'Size': 'Size',
  'Select': 'Select',
  'Gallery': 'Gallery',
  'Camera': 'Camera',
  'Verification Code': 'Verification Code',
};
